on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  NET_7_Pipeline:
    uses: SilverIncorporated/Pipelines/.github/workflows/BuildGHPackageDOTNET7.yml@main
    secrets: inherit

  NET_7_Deploy_to_UiPath:
    needs: NET_7_Pipeline
    uses: SilverIncorporated/Pipelines/.github/workflows/AddPackageToUiPath.yml@main
    secrets: inherit
    with:
      packageName: 

