on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  NET_6_Pipeline:
    uses: SilverIncorporated/Pipelines/.github/workflows/BuildMyGetPackageDOTNET6.yml@main
    secrets: inherit
