on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  NET_6_Pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: SilverIncorporated/BuildNETforUiPath
        with:
          secrets: inherit
