on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  NET_6_Pipeline:
    steps:
      - uses: SilverIncorporated/Pipelines/.github/workflows/BuildNETforUiPath.yml
        with:
          secrets: inherit