name: Test

on: 
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest    
    outputs: 
      Version: ${{ steps.v.outputs.version }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 #fetch-depth is needed for Semantic Version
      #Install and calculate the new version with GitVersion  
    - name: Show Github info
      uses: crazy-max/ghaction-dump-context@v1
      